version: "3.9"

services:
  jenkins:
    build:
      context: .
      args:
        HOST_DOCKER_GID: $HOST_DOCKER_GID
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins:/var/jenkins_home
    labels:
      - traefik.http.routers.jenkins.rule=Host(`jenkins.kalpas.in`)
      - traefik.http.routers.jenkins.tls=true
      - traefik.http.routers.jenkins.tls.certresolver=lets-encrypt
      - traefik.port=8080
    networks:
      - jenkins-network

volumes:
  jenkins:

networks:
  jenkins-network: